[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "glfw_template"
include-after = [
    "cmake/generate_shaders.cmake"
]

# See https://vcpkg.io/en/packages.html for available packages
# Chose a version from https://github.com/microsoft/vcpkg/releases
[vcpkg]
version = "2021.05.12"
packages = ["glfw3", "glew"]

# vcpkg will download the packages, but you still need to find them to use them
[find-package]
glfw3 = {}
GLEW = {}

[target.example]
type = "executable"
sources = [
    "src/example.cpp",
    "shaders/FragmentShader.glsl",
    "shaders/VertexShader.glsl",
]
link-libraries = ["glfw", "GLEW::GLEW"]
compile-features = ["cxx_std_11"]
cmake-after = """
generate_shaders(${CMKR_TARGET})
"""