[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "glfw_template"
include-after = [
    "cmake/generate_shaders.cmake"
]

# See https://github.com/microsoft/vcpkg#getting-started on how to use vcpkg
# Chose a version from https://github.com/microsoft/vcpkg/releases
# During CMake configuration you will be told how to find and link to the packages
[vcpkg]
version = "2020.11"
packages = ["glfw3", "GLEW"]

# vcpkg will download the packages, but you still need to find them to use them
[find-package]
glfw3 = {}
GLEW = {}

[target.example]
type = "executable"
sources = [
    "src/example.cpp",
    "shaders/FragmentShader.glsl",
    "shaders/VertexShader.glsl",
]
include-directories = [
    "${CMAKE_CURRENT_BINARY_DIR}/include"
]
link-libraries = ["glfw", "GLEW::GLEW"]
compile-features = ["cxx_std_11"]
cmake-after = """
generate_shaders(example)
"""